### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dariasc** [DishankJ/AniList-Darker#2]
Hey!

I really appreciate this awesome style, it looks amazing. I wanted to do some small modifications, mainly make it quite a bit darker, but this repository has no license so you retain all copyright, meaning no derivative works can be made. 

If allowing contributions/allowing changes is something you would like to allow I would recommend taking a look at the available open source licenses [https://choosealicense.com/](https://choosealicense.com/).

Thanks again for the awesome theme.

**Comment by DishankJ** [comment]
You are free to do anything with the stylesheet. In fact I'd love the fact that more people are using this.

**Comment by dariasc** [comment]
Thanks for the quick clarification :D
